### ISSUE TITLE
Les couleurs (vert jaune rouge) ne correspondent pas au remplissage.

### ISSUE THREAD

**Issue by manonvbk** [alexetmanon/vliller#32]
Il semble que le remplissage des vélos soit toujours Rouge, et le remplissage de la station, toujours Vert.
![19718384_10155383473508898_798226090_o](https://user-images.githubusercontent.com/22754291/27830368-6c4439b0-60c6-11e7-8853-6e8bec15cd35.png)
![19749414_10155383472393898_1735838287_o](https://user-images.githubusercontent.com/22754291/27830369-6c48f6d0-60c6-11e7-88f9-a131a28e1e4f.png)

**Comment by blckshrk** [comment]
Je confirme qu'il y a un bug à ce niveau. C'est moi c'est tout le temps vert. Je pense savoir qu'on ça peut venir.

Merci pour le rapport de bug!
