### ISSUE TITLE
L'info "indisponible" des stations ne s'affiche pas

### ISSUE THREAD

**Issue by manonvbk** [alexetmanon/vliller#33]
Bug transpole ou Vliller?
Bug vu le 3 juillet
![19718384_10155383473508898_798226090_o](https://user-images.githubusercontent.com/22754291/27830424-aa42beb2-60c6-11e7-9729-242b0d407900.png)
![19840125_10155383477763898_882040804_o](https://user-images.githubusercontent.com/22754291/27830425-aa448bc0-60c6-11e7-82a9-f3586e8ded06.jpg)

**Comment by alexbonhomme** [comment]
Dans ce cas c'est sans doute un manque d'information de la part de Transpole.

J'ai revu et corrigé toute la partie affichage des station indisponibles. Ça devrait être beaucoup mieux ;)
