### ISSUE TITLE
Impossible de fermer l'infobulle de position

### ISSUE THREAD

**Issue by Trillon008** [alexetmanon/vliller#41]
Quand l'appli démarre avec la la géolocalisation désactivée, un popup pour ouvrir les paramètres et l'activer ou annuler s'affiche. Impossible de fermer ce popup. 
Petit plus rigolo, il est possible d'utiliser les fonctionnalités de l'appli en arrière plan. en gardant le popup affiché. 

Android 7.1

**Comment by alexbonhomme** [comment]
Salut @Trillon008 

Merci pour ton retour. Si je comprends bien le bouton "annuler" ne fonctionne pas ? Est-ce que tu arrives à reproduire le bug de manière systématique ?

J'ai pas vraiment le temps de m'en occuper en ce moment, je vais essayer de regarder ce weekend, mais n'hésite pas à creuser de ton coté si tu as 5 minute :-) Je pense que c'est un bug dans `src/effects/location.ts`. J'ai revu l'architecture de l'application avec le design pattern Redux, donc c'est possible que j'ai oublié ce cas de figure la...

**Comment by alexbonhomme** [comment]
Peut-être relié à #27

**Comment by Trillon008** [comment]
Salut @alexbonhomme 

Pour te donner plus d'infos: 
  - Oui, le bug est systématique. 
  - Le bouton "annuler ne fonctionne pas ni celui "ouvrir les paramètres" 

En fait c'est comme si ce popup ne devait pas être là. Les events ne sont pas pris en compte dessus. Appuyer deux fois sur ouvrir les paramètres zoom sur la carte. Swipper fait bouger la carte. 

En revanche appuyer sur le logo Vliller en haut à gauche le fait disparaître. 
Si je peux je jetterai un coup d’œil sur le code.

**Comment by cmnt** [comment]
Salut,

De mon coté, je n'arrive pas à reproduire le bug de mon coté (Android 6.0.1).

**Comment by alexbonhomme** [comment]
Hello,

J'ai reproduit le bug sur mon Nexus également. J'ai trouvé la source, je planche sur un fix.

@cmnt tu devrais l'avoir aussi. Tu as quelle version de l'application ?

**Comment by cmnt** [comment]
@alexbonhomme j'ai la version 1.9.0... (et je n'ai pas de MAJ proposés sur le playstore.

**Comment by alexbonhomme** [comment]
@cmnt Ok tu as le bug du beta testeur ;-) Il faut que tu supprime l'application et que tu la réinstalle. Je ne sais pas pourquoi, mais les personnes inscrites au beta test ne reçoivent que les versions beta. Or, j'ai arrêté la beta à la `1.9.0`. Pourtant sur le play store elle est sensée être synchro avec la prod...

**Comment by cmnt** [comment]
@alexbonhomme Effectivement ! Du coup je confirme le bug !

**Comment by alexbonhomme** [comment]
@Trillon008 @cmnt Le problème devrait être réglé dans la version `2.4.3` ;-)

**Comment by Trillon008** [comment]
Nouvelle version reçue ce matin, problème effectivement corrigé ;)
Merci bien
