### ISSUE TITLE
Header non cliquable, la carte passe par dessus

### ISSUE THREAD

**Issue by manonvbk** [alexetmanon/vliller#46]
Les boutons du header ne sont pas cliquables (cadenas, geoloc, menu). 
Au lieu de ça, le contrôle de la carte est étendu jusqu'en dessous du header.

**Comment by alexbonhomme** [comment]
@manonvbk Toujours d'actualité avec le 2.5.6 ?

**Comment by manonvbk** [comment]
Non ça semble fonctionner.
J'ai cliqué comme une maboule sur le header et j'ai juste réussi à ouvrir
le cadenas ^^

*Manon Verbeke*
+ 33 (0) 6 85 15 36 83
*-*
*alex et manon*
concepteurs d'applications mobiles
www.alexetmanon.com

2017-11-07 20:02 GMT+01:00 Alexandre Bonhomme <notifications@github.com>:

**Comment by alexbonhomme** [comment]
Ok super, je clos l'issue alors ;-)
