### ISSUE TITLE
Crash sur Android

### ISSUE THREAD

**Issue by alexbonhomme** [alexetmanon/vliller#6]
A préciser

**Comment by btrd** [comment]
Jamais eu de soucis personnellement et je l'utilise presque tous les jours.

**Comment by blckshrk** [comment]
Merci de ton retour !
Je n'ai pas eu le temps de creuser plus, mais il semble que sur les smartphones moins puissants, il y ai parfois un crash au niveau du chargement de la map (à cause d'un null pointer exception).

Sinon, pour information, on travaille actuellement sur une V2 qui ne devrait pas tarder à sortir (avec en autre une gestion des favoris) :-) stay tuned!
