### ISSUE TITLE
Mise à jour du plugin Google Maps vers la V2

### ISSUE THREAD

**Issue by alexbonhomme** [alexetmanon/vliller#8]
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/v2-beta

**Comment by blckshrk** [comment]
Solution alternative à étudier : https://github.com/Telerik-Verified-Plugins/Mapbox

**Comment by blckshrk** [comment]
Standy à cause d'un bug lors de l'ajout d'un grand nombre de marker sur la v2 du plugin.

**Comment by blckshrk** [comment]
La versions actuelles est toujours plus lente que la V1. Solution envisagées : 

- A cours terme : augmenter le plugin V2 avec une fonction d'ajout des marqueurs par lot (bulk)
- A moyen terme : modifier le plugin actuel pour en faire un plugin dédié à Vliller (ne garder que les fonctions essentielles)

**Comment by alexbonhomme** [comment]
Done #59
